from enum import Enum

class TaskAction(str, Enum):
    REPROCESS = "REPROCESS"
    METADATA_REFRESH = "METADATA_REFRESH"
    SUBTITLE_REFRESH = "SUBTITLE_REFRESH"
    ARTWORK_REFRESH = "ARTWORK_REFRESH"